# AUTO-COMMENTED FOR CODEX: each meaningful executable line has an adjacent purpose comment.
"""Generate the catalog-wide server-authority inventory for issue #191."""

# Import JSON support for the deterministic machine-readable certification artifact.
import json
# Import pathlib so generation remains independent of the caller working directory.
from pathlib import Path
# Import regular expressions for the deliberately small OpenAPI path/method scanner.
import re
# Import sys so direct script execution can load the repository package.
import sys

# Resolve the repository root from this script location.
ROOT = Path(__file__).resolve().parents[1]
# Add the repository root before loading the canonical catalog facade.
sys.path.insert(0, str(ROOT))
# Import the catalog only after the repository root is available.
from casino.config import GAMES

# Point to the checked-in certification artifact generated by this script.
MATRIX_PATH = ROOT / "contracts" / "compatibility" / "server-authority-matrix.json"
# Recognize every HTTP method that can mutate game or control state.
MUTATION_METHODS = frozenset({"post", "put", "patch", "delete"})
# Require every catalog entry to certify the complete hostile-client scenario set.
MANDATORY_ASSURANCES = (
    "raw_api_mutation", "cross_user_isolation", "legal_action_and_turn", "rng_outcome_and_payout", "wallet_and_ledger", "replay_conflict_lost_response_restart", "concurrency", "admin_authority", "client_tamper_refresh",  # Enumerate every mandatory scenario on the owned tuple line.
)
# Define the fields removed centrally before any game handler sees a request.
PROTECTED_FIELDS = (
    "user_id", "role", "roles", "admin", "is_admin", "wallet_id", "balance", "token_balance", "result", "force_result", "outcome", "payout", "winnings", "settlement", "settlement_total", "rng", "rng_seed", "seed", "random_seed", "card_order", "cards", "deck", "shoe", "dice", "reels", "reel_positions", "pocket", "wheel_pocket", "win", "win_state", "free_spins", "bonus", "jackpot", "state", "phase", "turn", "version",  # Keep the generated policy byte-for-byte aligned with runtime protection.
)


# Prove one game module is wired to the shared settlement boundary before certifying it. (LEDGER-032)
def settlement_boundary(game_id: str) -> str:
    # Resolve the registered game package without relying on a handwritten cohort table.
    game_root = ROOT / "casino" / "games" / game_id
    # Join executable sources so direct and shared-simple game shapes are handled uniformly.
    source = "\n".join(path.read_text(encoding="utf-8") for path in sorted(game_root.rglob("*.py")))
    # Accept a direct shared-gateway import or delegation through the shared simple-game core.
    if "GameSettlementGateway" in source or "SimpleWagerGame" in source:
        # Publish the exact common owner used by all financial actions.
        return "casino.core.settlement.GameSettlementGateway"
    # Fail generation when a registered game can no longer prove the governed interface.
    raise RuntimeError(f"catalog game {game_id} does not use the shared settlement boundary")


# Parse mutation operations from the repository's stable two-space OpenAPI layout.
def mutation_actions(contract_path: Path) -> list[dict]:
    # Collect explicit method and path pairs in source order.
    actions = []
    # Track the current OpenAPI path while scanning nested method declarations.
    current_path = None
    # Read the contract as text so validation does not add a runtime YAML dependency.
    for line in contract_path.read_text(encoding="utf-8").splitlines():
        # Detect one path key at exactly the established paths indentation level.
        path_match = re.match(r"^  (/api/v1/[^:]+):\s*$", line)
        # Update the current path whenever a new route begins.
        if path_match:
            # Preserve the published OpenAPI template exactly.
            current_path = path_match.group(1)
            # Continue because a path line cannot also declare a method.
            continue
        # Detect one HTTP method beneath the current path.
        method_match = re.match(r"^    ([a-z]+):\s*$", line)
        # Record only state-changing methods and ignore response/schema nesting.
        if current_path and method_match and method_match.group(1) in MUTATION_METHODS:
            # Add an explicit action inventory row with uniform authority ownership.
            actions.append({
                # Publish the method in conventional uppercase form.
                "method": method_match.group(1).upper(),
                # Preserve the contract path as the canonical action identity.
                "path": current_path,
                # Bind accepted fields to the frozen OpenAPI request schema and route template.
                "client_intent": "openapi_request_schema_and_path_choices_only",
                # Require server validation for legal state, phase, turn, wager, and ownership.
                "server_validation": "authenticated_route_and_game_service",
                # Require outcomes and randomness to come only from the server engine.
                "engine_outcome": "server_game_engine",
                # Require monetary effects to use the storage transaction and ledger when applicable.
                "storage_transaction": "storage_and_ledger_when_financial",
                # Restrict the response to a server-projected authoritative receipt.
                "response_projection": "server_authoritative_projection",
            })
    # Return every mutation/control action found in the game contract.
    return actions


# Resolve the most focused checked-in API evidence file for one catalog game.
def evidence_path(game_id: str) -> str:
    # Define supported per-game test locations in preference order.
    candidates = (
        ROOT / "tests" / "games" / game_id / "test_api.py",  # Prefer the standard game test tree.
        ROOT / "casino" / "games" / game_id / "tests" / "test_api.py",  # Support older module-local test ownership.
        ROOT / "tests" / "api" / f"{game_id}_api_tests.py",  # Support focused shared API test modules.
    )
    # Return the first focused evidence file that exists.
    for candidate in candidates:
        # Use repository-relative POSIX paths for stable cross-platform JSON.
        if candidate.exists():
            # Return the canonical portable path.
            return candidate.relative_to(ROOT).as_posix()
    # Use the integrated private-session API suite for legacy catalog modules.
    return "tests/run_tests.py"


# Build the complete deterministic certification matrix from canonical catalog and contracts.
def build_matrix() -> dict:
    # Collect one authority record for every current registered catalog entry.
    games = []
    # Walk the ordered catalog so the generated artifact matches public registration order.
    for game in GAMES:
        # Require one primary contract because catalog validation already forbids missing contracts.
        contract = game["contracts"][0]
        # Parse all money-bearing and control mutations from the owned contract.
        actions = mutation_actions(ROOT / contract)
        # Reject an empty action inventory because such a game cannot be certified.
        if not actions:
            # Fail generation with the owning catalog id for a focused repair.
            raise RuntimeError(f"catalog game {game['id']} exposes no certifiable mutation action")
        # Derive the financial boundary from the registered game's checked-in implementation.
        game_settlement_boundary = settlement_boundary(game["id"])
        # Bind every financial action assertion to the exact implementation-derived owner.
        for action in actions:
            # Replace the generic historical label with the common settlement interface.
            action["storage_transaction"] = game_settlement_boundary
        # Add the complete game-level authority and evidence record.
        games.append({
            # Preserve the module-owned catalog identity.
            "game_id": game["id"],
            # Link the inventory to its frozen public contract.
            "contract": contract,
            # Record the source-proven common money interface for this exact catalog module.
            "settlement_interface": game_settlement_boundary,
            # Inventory every discovered state-changing action explicitly.
            "actions": actions,
            # Require all hostile-client categories for every registered game.
            "assurances": list(MANDATORY_ASSURANCES),
            # Link focused and integrated runtime evidence without copying test logic.
            "evidence": [evidence_path(game["id"]), "tests/run_tests.py", "tests/storage_tests.py"],
        })
    # Return the versioned current-catalog certification document.
    return {
        # Version the certification schema independently from application releases.
        "schema_version": 1,
        # Map the artifact to permanent issue #191 requirements.
        "requirements": [f"SEC-{index:03d}" for index in range(1, 10)],
        # Certify the four clients that share the same authenticated server boundary.
        "client_surfaces": ["browser", "pwa", "android", "ios"],
        # Record the catalog count so reviewers can compare coverage without manual counting.
        "catalog_game_count": len(games),
        # Explain how the explicit per-action inventory is derived and guarded.
        "action_source": "state-changing operations in each module-owned OpenAPI v1 contract",
        # Publish the exact hostile fields stripped before all game dispatch.
        "protected_fields": list(PROTECTED_FIELDS),
        # Publish the complete mandatory scenario set once for machine consumers.
        "mandatory_assurances": list(MANDATORY_ASSURANCES),
        # Identify the shared authority owners applied to every action row.
        "authority_owners": {
            "identity": "authenticated_server_session",  # Bind identity to authentication middleware.
            "legal_action_and_turn": "server_game_service",  # Bind legal state changes to the service.
            "rng_outcome_and_payout": "server_game_engine",  # Bind random results and math to the engine.
            "wallet_and_ledger": "casino.core.settlement.GameSettlementGateway",  # Bind money to the source-proven shared adapter.
            "receipt": "server_response_projection",  # Bind visible results to the server response.
        },
        # Include only games registered on the protected-main catalog used for this certification.
        "games": games,
    }


# Generate the checked-in artifact from canonical sources.
def main() -> int:
    # Serialize with stable indentation and trailing newline for reviewable diffs.
    MATRIX_PATH.write_text(json.dumps(build_matrix(), indent=2) + "\n", encoding="utf-8")
    # Report the exact generated path for local and CI logs.
    print(f"Wrote {MATRIX_PATH}")
    # Return success after the artifact is fully written.
    return 0


# Run generation only when invoked as a script.
if __name__ == "__main__":
    # Exit with the generator result so callers can fail fast.
    raise SystemExit(main())
