// AUTO-COMMENTED FOR CODEX: each meaningful executable line has an adjacent purpose comment.
// Import required dependency so this module can use its public functions or constants.
import { api, post, del } from '../core/api.js';
// Import required dependency so this module can use its public functions or constants.
import { money, toast, refreshBalance, safe } from '../core/ui.js';
// Import required dependency so this module can use its public functions or constants.
import { renderAutoplay } from '../core/autoplay.js';
// Import required dependency so this module can use its public functions or constants.
import { speak, clickSound } from '../core/voice.js';
// Import required dependency so this module can use its public functions or constants.
import { botPanelHtml, playBotRound } from '../core/bots.js';
// Store root so later code can read or update this value.
let root=null,state=null,paytable={},selected=new Set(),amount=5,autoBox=null,lastDraw=null,displayedDraw=[],botPanelCache='<p class="muted">Loading bot controllers...</p>',drawBusy=false;
// Define the updateBotPanel function that implements this UI or API behavior.
async function updateBotPanel(){botPanelCache=await botPanelHtml('keno'); const el=root?.querySelector('#botPanel'); if(el)el.innerHTML=botPanelCache;}
// Define the load function that implements this UI or API behavior.
async function load(){const d=await api('/api/v1/games/keno/state');state=d.state;paytable=d.paytable;render();await updateBotPanel();await refreshBalance();}
// Define the buyTicket function that implements this UI or API behavior.
async function buyTicket(){if(selected.size<1){toast('Pick at least one Keno number.');return null;}amount=Number(root.querySelector('#kenoAmount').value||amount);const d=await post('/api/v1/games/keno/tickets',{player_id:'human',amount,spots:[...selected]});state=d.state;paytable=d.paytable;render();await updateBotPanel();await refreshBalance();clickSound(500,.05);return d.ticket}
// Define the clearTicket function that implements this UI or API behavior.
async function clearTicket(id){const d=await del(`/api/v1/games/keno/tickets/${id}`,{player_id:'human'});state=d.state;paytable=d.paytable;render();await updateBotPanel();await refreshBalance();}
// Define the draw function that implements this UI or API behavior.
async function draw(show=true){if(drawBusy)return; drawBusy=true; try{if((state.open_tickets||[]).filter(t=>t.player_id==='human').length===0){const t=await buyTicket(); if(!t)return;} await playBotRound('keno'); const d=await post('/api/v1/games/keno/draw',{});state=d.state;paytable=d.paytable;lastDraw=d.draw;displayedDraw=[];render(); if(show){for(const n of d.draw.drawn){displayedDraw.push(n);render();clickSound(280+n*8,.035);await new Promise(r=>setTimeout(r,45));}} else {displayedDraw=d.draw.drawn;} render();await updateBotPanel();await refreshBalance();const human=d.settlements.find(s=>s.result.ticket.player_id==='human');if(show)speak(`Keno caught ${human?.result.catch_count||0} numbers`,'keno');} finally {drawBusy=false;}}
// Define the toggle function that implements this UI or API behavior.
function toggle(n){if(selected.has(n))selected.delete(n);else if(selected.size<20)selected.add(n);else toast('Keno allows up to 20 spots.');render();updateBotPanel();}
// Define the paytableHtml function that implements this UI or API behavior.
function paytableHtml(){return `<table class="mini-table"><tr><th>Spots</th><th>Pays by catches</th></tr>${Object.entries(paytable).map(([spots,row])=>`<tr><td>${spots}</td><td>${Object.entries(row).map(([c,m])=>`${c}: ${m}x`).join(' · ')}</td></tr>`).join('')}</table>`}
// Define the render function that implements this UI or API behavior.
function render(){const drawn=new Set(displayedDraw.length?displayedDraw:(lastDraw?.drawn||[]));const humanResult=lastDraw?.results?.find(r=>r.ticket.player_id==='human');root.innerHTML=`<div class="game-layout three-col stable-game"><section class="panel control-rail"><h2>Keno</h2><label>Ticket amount<input id="kenoAmount" data-testid="keno-amount" type="number" min="1" value="${amount}"></label><div class="row"><button id="quick5">Quick pick 5</button><button id="quick10">Quick pick 10</button><button id="clearSel">Clear picks</button></div><button id="buy" data-testid="keno-buy" class="gold">Buy ticket</button><button id="draw" data-testid="keno-draw" class="primary">Draw 20</button><div id="auto"></div><div id="botPanel">${botPanelCache}</div></section><section class="panel game-stage"><h2>Pick 1-20 spots</h2><div class="keno-grid" data-testid="keno-grid">${Array.from({length:80},(_,i)=>i+1).map(n=>`<button class="keno-num ${selected.has(n)?'selected':''} ${drawn.has(n)?'drawn':''} ${humanResult?.catches?.includes(n)?'catch':''}" data-num="${n}" data-testid="keno-num-${n}">${n}</button>`).join('')}</div><div class="result-box fixed-result">Selected: ${selected.size}/20${humanResult?`<br><b>Catches:</b> ${humanResult.catch_count} (${humanResult.catches.join(', ')}) · <b>Payout:</b> ${money(humanResult.payout)}`:''}</div></section><section class="panel details-drawer"><h3>Open tickets</h3><div class="bet-list stable-list">${(state.open_tickets||[]).filter(t=>t.player_id==='human').map(t=>`<div class="bet-item"><span>${t.spots.join(', ')}</span><b>${money(t.amount)}</b><button class="danger" data-clear="${t.ticket_id}">×</button></div>`).join('')||'<p class="muted">No ticket.</p>'}</div><h3>Drawn balls</h3><div class="called-balls">${[...(drawn||[])].sort((a,b)=>a-b).map(n=>`<span class="ball">${n}</span>`).join('')}</div><h3>Paytable</h3><div class="scrollbox">${paytableHtml()}</div><h3>Bot results</h3>${lastDraw?`<table class="mini-table">${lastDraw.results.filter(r=>r.ticket.player_id!=='human').map(r=>`<tr><td>${r.ticket.player_id}</td><td>${r.catch_count} catches</td><td>${money(r.payout)}</td></tr>`).join('')}</table>`:''}</section></div>`;root.querySelectorAll('.keno-num').forEach(b=>b.onclick=()=>toggle(Number(b.dataset.num)));root.querySelector('#kenoAmount').onchange=e=>{amount=Number(e.target.value||5)};root.querySelector('#quick5').onclick=()=>{selected=new Set(rand(5));render();updateBotPanel();};root.querySelector('#quick10').onclick=()=>{selected=new Set(rand(10));render();updateBotPanel();};root.querySelector('#clearSel').onclick=()=>{selected.clear();render();updateBotPanel();};root.querySelector('#buy').onclick=buyTicket;root.querySelector('#draw').onclick=()=>draw(true);root.querySelectorAll('[data-clear]').forEach(b=>b.onclick=()=>clearTicket(b.dataset.clear));autoBox=renderAutoplay({id:'keno',plan:{type:'repeat_ticket'},onTick:async()=>draw(false)});root.querySelector('#auto').append(autoBox);}
// Define the rand function that implements this UI or API behavior.
function rand(n){const a=[];while(a.length<n){const x=1+Math.floor(Math.random()*80);if(!a.includes(x))a.push(x)}return a.sort((a,b)=>a-b)}
// Export this symbol so other modules can use it through the public module boundary.
export const KenoGame={id:'keno',label:'Keno',async mount(node){root=node;await load();},unmount(){if(autoBox?._stop)autoBox._stop();root=null;}};
